xcopy C:\xampp\htdocs\dev\build\css\custom.css C:\xampp\htdocs\prod\build\css\custom.css /d /y
xcopy C:\xampp\htdocs\dev\build\css\custom.min.css C:\xampp\htdocs\prod\build\css\custom.min.css /d /y
xcopy C:\xampp\htdocs\dev\build\images\back_disabled.png C:\xampp\htdocs\prod\build\images\back_disabled.png /d /y
xcopy C:\xampp\htdocs\dev\build\images\back_enabled.png C:\xampp\htdocs\prod\build\images\back_enabled.png /d /y
xcopy C:\xampp\htdocs\dev\build\images\back_enabled_hover.png C:\xampp\htdocs\prod\build\images\back_enabled_hover.png /d /y
xcopy C:\xampp\htdocs\dev\build\images\forward_disabled.png C:\xampp\htdocs\prod\build\images\forward_disabled.png /d /y
xcopy C:\xampp\htdocs\dev\build\images\forward_enabled.png C:\xampp\htdocs\prod\build\images\forward_enabled.png /d /y
xcopy C:\xampp\htdocs\dev\build\images\forward_enabled_hover.png C:\xampp\htdocs\prod\build\images\forward_enabled_hover.png /d /y
xcopy C:\xampp\htdocs\dev\build\images\loading.gif C:\xampp\htdocs\prod\build\images\loading.gif /d /y
xcopy C:\xampp\htdocs\dev\build\js\custom.js C:\xampp\htdocs\prod\build\js\custom.js /d /y
xcopy C:\xampp\htdocs\dev\build\js\custom.min.js C:\xampp\htdocs\prod\build\js\custom.min.js /d /y
xcopy C:\xampp\htdocs\dev\build\js\custom.minOld.js C:\xampp\htdocs\prod\build\js\custom.minOld.js /d /y
xcopy C:\xampp\htdocs\dev\dennis\css\maps\jquery-jvectormap-2.0.3.css C:\xampp\htdocs\prod\dennis\css\maps\jquery-jvectormap-2.0.3.css /d /y
xcopy C:\xampp\htdocs\dev\dennis\css\animate.css C:\xampp\htdocs\prod\dennis\css\animate.css /d /y
xcopy C:\xampp\htdocs\dev\dennis\css\bootstrap-editable.css C:\xampp\htdocs\prod\dennis\css\bootstrap-editable.css /d /y
xcopy C:\xampp\htdocs\dev\dennis\css\bootstrap-table.min.css C:\xampp\htdocs\prod\dennis\css\bootstrap-table.min.css /d /y
xcopy C:\xampp\htdocs\dev\dennis\css\datepicker.min.css C:\xampp\htdocs\prod\dennis\css\datepicker.min.css /d /y
xcopy C:\xampp\htdocs\dev\dennis\css\jquery-ui.min.css C:\xampp\htdocs\prod\dennis\css\jquery-ui.min.css /d /y
xcopy C:\xampp\htdocs\dev\dennis\css\local_wizard.css C:\xampp\htdocs\prod\dennis\css\local_wizard.css /d /y
xcopy C:\xampp\htdocs\dev\dennis\css\style.css C:\xampp\htdocs\prod\dennis\css\style.css /d /y
xcopy C:\xampp\htdocs\dev\dennis\img\clear.png C:\xampp\htdocs\prod\dennis\img\clear.png /d /y
xcopy C:\xampp\htdocs\dev\dennis\img\loading.gif C:\xampp\htdocs\prod\dennis\img\loading.gif /d /y
xcopy C:\xampp\htdocs\dev\dennis\js\datepicker\daterangepicker.js C:\xampp\htdocs\prod\dennis\js\datepicker\daterangepicker.js /d /y
xcopy C:\xampp\htdocs\dev\dennis\js\moment\moment.min.js C:\xampp\htdocs\prod\dennis\js\moment\moment.min.js /d /y
xcopy C:\xampp\htdocs\dev\dennis\js\ajax-bootstrap-select.js C:\xampp\htdocs\prod\dennis\js\ajax-bootstrap-select.js /d /y
xcopy C:\xampp\htdocs\dev\dennis\js\ajax-bootstrap-select.min.js C:\xampp\htdocs\prod\dennis\js\ajax-bootstrap-select.min.js /d /y
xcopy C:\xampp\htdocs\dev\dennis\js\bootstrap-editable.js C:\xampp\htdocs\prod\dennis\js\bootstrap-editable.js /d /y
xcopy C:\xampp\htdocs\dev\dennis\js\bootstrap-select.js C:\xampp\htdocs\prod\dennis\js\bootstrap-select.js /d /y
xcopy C:\xampp\htdocs\dev\dennis\js\bootstrap-table-editable.js C:\xampp\htdocs\prod\dennis\js\bootstrap-table-editable.js /d /y
xcopy C:\xampp\htdocs\dev\dennis\js\bootstrap-table.min.js C:\xampp\htdocs\prod\dennis\js\bootstrap-table.min.js /d /y
xcopy C:\xampp\htdocs\dev\dennis\js\datepicker.js C:\xampp\htdocs\prod\dennis\js\datepicker.js /d /y
xcopy C:\xampp\htdocs\dev\dennis\js\datepicker.min.js C:\xampp\htdocs\prod\dennis\js\datepicker.min.js /d /y
xcopy C:\xampp\htdocs\dev\dennis\js\jquery-ui.min.js C:\xampp\htdocs\prod\dennis\js\jquery-ui.min.js /d /y
xcopy C:\xampp\htdocs\dev\dennis\js\local_wizard.js C:\xampp\htdocs\prod\dennis\js\local_wizard.js /d /y
xcopy C:\xampp\htdocs\dev\dennis\js\sammy.js C:\xampp\htdocs\prod\dennis\js\sammy.js /d /y
xcopy C:\xampp\htdocs\dev\dennis\js\sammy.min.js C:\xampp\htdocs\prod\dennis\js\sammy.min.js /d /y
xcopy C:\xampp\htdocs\dev\dennis\js\sammy.template.js C:\xampp\htdocs\prod\dennis\js\sammy.template.js /d /y
xcopy C:\xampp\htdocs\dev\dennis\js\wow.min.js C:\xampp\htdocs\prod\dennis\js\wow.min.js /d /y
xcopy C:\xampp\htdocs\dev\dennis\report\font\courier.php C:\xampp\htdocs\prod\dennis\report\font\courier.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\report\font\courierb.php C:\xampp\htdocs\prod\dennis\report\font\courierb.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\report\font\courierbi.php C:\xampp\htdocs\prod\dennis\report\font\courierbi.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\report\font\courieri.php C:\xampp\htdocs\prod\dennis\report\font\courieri.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\report\font\helvetica.php C:\xampp\htdocs\prod\dennis\report\font\helvetica.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\report\font\helveticab.php C:\xampp\htdocs\prod\dennis\report\font\helveticab.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\report\font\helveticabi.php C:\xampp\htdocs\prod\dennis\report\font\helveticabi.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\report\font\helveticai.php C:\xampp\htdocs\prod\dennis\report\font\helveticai.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\report\font\ManuskriptGothischUNZ1A.php C:\xampp\htdocs\prod\dennis\report\font\ManuskriptGothischUNZ1A.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\report\font\ManuskriptGothischUNZ1A.z C:\xampp\htdocs\prod\dennis\report\font\ManuskriptGothischUNZ1A.z /d /y
xcopy C:\xampp\htdocs\dev\dennis\report\font\symbol.php C:\xampp\htdocs\prod\dennis\report\font\symbol.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\report\font\times.php C:\xampp\htdocs\prod\dennis\report\font\times.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\report\font\timesb.php C:\xampp\htdocs\prod\dennis\report\font\timesb.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\report\font\timesbi.php C:\xampp\htdocs\prod\dennis\report\font\timesbi.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\report\font\timesi.php C:\xampp\htdocs\prod\dennis\report\font\timesi.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\report\font\zapfdingbats.php C:\xampp\htdocs\prod\dennis\report\font\zapfdingbats.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\report\fpdf.php C:\xampp\htdocs\prod\dennis\report\fpdf.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\report\Import_Entry.php C:\xampp\htdocs\prod\dennis\report\Import_Entry.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\report\ManuskriptGothischUNZ1A.php C:\xampp\htdocs\prod\dennis\report\ManuskriptGothischUNZ1A.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\report\ManuskriptGothischUNZ1A.z C:\xampp\htdocs\prod\dennis\report\ManuskriptGothischUNZ1A.z /d /y
xcopy C:\xampp\htdocs\dev\dennis\report\rpt_cancelled_orders.php C:\xampp\htdocs\prod\dennis\report\rpt_cancelled_orders.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\report\rpt_cancelled_receipts.php C:\xampp\htdocs\prod\dennis\report\rpt_cancelled_receipts.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\report\rpt_charges_collection.php C:\xampp\htdocs\prod\dennis\report\rpt_charges_collection.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\report\rpt_daily_order.php C:\xampp\htdocs\prod\dennis\report\rpt_daily_order.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\report\rpt_print_bol.php C:\xampp\htdocs\prod\dennis\report\rpt_print_bol.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\report\rpt_print_order.php C:\xampp\htdocs\prod\dennis\report\rpt_print_order.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\report\rpt_print_receipt.php C:\xampp\htdocs\prod\dennis\report\rpt_print_receipt.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\report\rpt_receipt_listing.php C:\xampp\htdocs\prod\dennis\report\rpt_receipt_listing.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\report\testReport1.php C:\xampp\htdocs\prod\dennis\report\testReport1.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\scripts\app.js C:\xampp\htdocs\prod\dennis\scripts\app.js /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\billoflading_Service.php C:\xampp\htdocs\prod\dennis\service\billoflading_Service.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\bill_of_ladingService.php C:\xampp\htdocs\prod\dennis\service\bill_of_ladingService.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\bill_of_lading_containerService.php C:\xampp\htdocs\prod\dennis\service\bill_of_lading_containerService.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\bill_of_lading_detailService.php C:\xampp\htdocs\prod\dennis\service\bill_of_lading_detailService.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\bill_of_lading_other_chargeService.php C:\xampp\htdocs\prod\dennis\service\bill_of_lading_other_chargeService.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\charge_itemService.php C:\xampp\htdocs\prod\dennis\service\charge_itemService.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\commodityService.php C:\xampp\htdocs\prod\dennis\service\commodityService.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\container_size_typeService.php C:\xampp\htdocs\prod\dennis\service\container_size_typeService.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\countryService.php C:\xampp\htdocs\prod\dennis\service\countryService.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\currencyService.php C:\xampp\htdocs\prod\dennis\service\currencyService.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\custom_officeService.php C:\xampp\htdocs\prod\dennis\service\custom_officeService.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\dashboard_stats.php C:\xampp\htdocs\prod\dennis\service\dashboard_stats.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\edi_translationService.php C:\xampp\htdocs\prod\dennis\service\edi_translationService.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\load_Service.php C:\xampp\htdocs\prod\dennis\service\load_Service.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\menu_itemService.php C:\xampp\htdocs\prod\dennis\service\menu_itemService.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\order_Service.php C:\xampp\htdocs\prod\dennis\service\order_Service.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\packageService.php C:\xampp\htdocs\prod\dennis\service\packageService.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\portService.php C:\xampp\htdocs\prod\dennis\service\portService.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\receiptService.php C:\xampp\htdocs\prod\dennis\service\receiptService.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\receipt_detailService.php C:\xampp\htdocs\prod\dennis\service\receipt_detailService.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\receipt_Service.php C:\xampp\htdocs\prod\dennis\service\receipt_Service.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\score_scaleService.php C:\xampp\htdocs\prod\dennis\service\score_scaleService.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\shipment_orderService.php C:\xampp\htdocs\prod\dennis\service\shipment_orderService.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\system_valuesService.php C:\xampp\htdocs\prod\dennis\service\system_valuesService.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\translation_sourceService.php C:\xampp\htdocs\prod\dennis\service\translation_sourceService.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\user_optionService.php C:\xampp\htdocs\prod\dennis\service\user_optionService.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\user_profileService.php C:\xampp\htdocs\prod\dennis\service\user_profileService.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\vesselService.php C:\xampp\htdocs\prod\dennis\service\vesselService.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\VoyageService.php C:\xampp\htdocs\prod\dennis\service\VoyageService.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\service\voyage_containerService.php C:\xampp\htdocs\prod\dennis\service\voyage_containerService.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\Vendor\css\bootstrap-select.min.css C:\xampp\htdocs\prod\dennis\Vendor\css\bootstrap-select.min.css /d /y
xcopy C:\xampp\htdocs\dev\dennis\Vendor\css\bootstrap-table.min.css C:\xampp\htdocs\prod\dennis\Vendor\css\bootstrap-table.min.css /d /y
xcopy C:\xampp\htdocs\dev\dennis\Vendor\css\bootstrap.min.css C:\xampp\htdocs\prod\dennis\Vendor\css\bootstrap.min.css /d /y
xcopy C:\xampp\htdocs\dev\dennis\Vendor\css\toastr.min.css C:\xampp\htdocs\prod\dennis\Vendor\css\toastr.min.css /d /y
xcopy C:\xampp\htdocs\dev\dennis\Vendor\fonts\glyphicons-halflings-regular.eot C:\xampp\htdocs\prod\dennis\Vendor\fonts\glyphicons-halflings-regular.eot /d /y
xcopy C:\xampp\htdocs\dev\dennis\Vendor\fonts\glyphicons-halflings-regular.svg C:\xampp\htdocs\prod\dennis\Vendor\fonts\glyphicons-halflings-regular.svg /d /y
xcopy C:\xampp\htdocs\dev\dennis\Vendor\fonts\glyphicons-halflings-regular.ttf C:\xampp\htdocs\prod\dennis\Vendor\fonts\glyphicons-halflings-regular.ttf /d /y
xcopy C:\xampp\htdocs\dev\dennis\Vendor\fonts\glyphicons-halflings-regular.woff C:\xampp\htdocs\prod\dennis\Vendor\fonts\glyphicons-halflings-regular.woff /d /y
xcopy C:\xampp\htdocs\dev\dennis\Vendor\fonts\glyphicons-halflings-regular.woff2 C:\xampp\htdocs\prod\dennis\Vendor\fonts\glyphicons-halflings-regular.woff2 /d /y
xcopy C:\xampp\htdocs\dev\dennis\Vendor\js\bootstrap-select.min.js C:\xampp\htdocs\prod\dennis\Vendor\js\bootstrap-select.min.js /d /y
xcopy C:\xampp\htdocs\dev\dennis\Vendor\js\bootstrap-table.min.js C:\xampp\htdocs\prod\dennis\Vendor\js\bootstrap-table.min.js /d /y
xcopy C:\xampp\htdocs\dev\dennis\Vendor\js\bootstrap.min.js C:\xampp\htdocs\prod\dennis\Vendor\js\bootstrap.min.js /d /y
xcopy C:\xampp\htdocs\dev\dennis\Vendor\js\jquery-ui.js C:\xampp\htdocs\prod\dennis\Vendor\js\jquery-ui.js /d /y
xcopy C:\xampp\htdocs\dev\dennis\Vendor\js\jquery.min.js C:\xampp\htdocs\prod\dennis\Vendor\js\jquery.min.js /d /y
xcopy C:\xampp\htdocs\dev\dennis\Vendor\js\toastr.min.js C:\xampp\htdocs\prod\dennis\Vendor\js\toastr.min.js /d /y
xcopy C:\xampp\htdocs\dev\dennis\api.php C:\xampp\htdocs\prod\dennis\api.php /d /y

xcopy C:\xampp\htdocs\dev\dennis\billOfLading_Admin_Processed.html C:\xampp\htdocs\prod\dennis\billOfLading_Admin_Processed.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\maintain_exchange.html C:\xampp\htdocs\prod\dennis\maintain_exchange.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\batch_order.html C:\xampp\htdocs\prod\dennis\batch_order.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\billOfLading_Enquiry.html C:\xampp\htdocs\prod\dennis\billOfLading_Enquiry.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\billOfLading_History_Enquiry.html C:\xampp\htdocs\prod\dennis\billOfLading_History_Enquiry.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\calendar.html C:\xampp\htdocs\prod\dennis\calendar.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\config.php C:\xampp\htdocs\prod\dennis\config.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\default.png C:\xampp\htdocs\prod\dennis\default.png /d /y
xcopy C:\xampp\htdocs\dev\dennis\editInPlace.html C:\xampp\htdocs\prod\dennis\editInPlace.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\exportAnsix12.html C:\xampp\htdocs\prod\dennis\exportAnsix12.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\exportAsycuda.html C:\xampp\htdocs\prod\dennis\exportAsycuda.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\exportPCS.html C:\xampp\htdocs\prod\dennis\exportPCS.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\importManifest.html C:\xampp\htdocs\prod\dennis\importManifest.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\index.html C:\xampp\htdocs\prod\dennis\index.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\invoice.html C:\xampp\htdocs\prod\dennis\invoice.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\loadDBTables.php C:\xampp\htdocs\prod\dennis\loadDBTables.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\maintain_Bill_Of_Lading.html C:\xampp\htdocs\prod\dennis\maintain_Bill_Of_Lading.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\Maintain_Charges.html C:\xampp\htdocs\prod\dennis\Maintain_Charges.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\maintain_commodity.html C:\xampp\htdocs\prod\dennis\maintain_commodity.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\maintain_container_size_type.html C:\xampp\htdocs\prod\dennis\maintain_container_size_type.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\maintain_country.html C:\xampp\htdocs\prod\dennis\maintain_country.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\maintain_currency.html C:\xampp\htdocs\prod\dennis\maintain_currency.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\maintain_gct_rates.html C:\xampp\htdocs\prod\dennis\maintain_gct_rates.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\maintain_package.html C:\xampp\htdocs\prod\dennis\maintain_package.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\maintain_port.html C:\xampp\htdocs\prod\dennis\maintain_port.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\maintain_user.html C:\xampp\htdocs\prod\dennis\maintain_user.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\maintain_vessel.html C:\xampp\htdocs\prod\dennis\maintain_vessel.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\Maintain_Voyage.html C:\xampp\htdocs\prod\dennis\Maintain_Voyage.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\manage_order.html C:\xampp\htdocs\prod\dennis\manage_order.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\manage_receipts.html C:\xampp\htdocs\prod\dennis\manage_receipts.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\numbersToWords.php C:\xampp\htdocs\prod\dennis\numbersToWords.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\rpt_cancel_orders.html C:\xampp\htdocs\prod\dennis\rpt_cancel_orders.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\rpt_cancel_receipts.html C:\xampp\htdocs\prod\dennis\rpt_cancel_receipts.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\rpt_collections_by_item.html C:\xampp\htdocs\prod\dennis\rpt_collections_by_item.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\rpt_daily_orders.html C:\xampp\htdocs\prod\dennis\rpt_daily_orders.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\rpt_excel.html C:\xampp\htdocs\prod\dennis\rpt_excel.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\rpt_receipt_listing.html C:\xampp\htdocs\prod\dennis\rpt_receipt_listing.html /d /y
xcopy C:\xampp\htdocs\dev\dennis\service.php C:\xampp\htdocs\prod\dennis\service.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\sql.txt C:\xampp\htdocs\prod\dennis\sql.txt /d /y
xcopy C:\xampp\htdocs\dev\dennis\tables.json C:\xampp\htdocs\prod\dennis\tables.json /d /y
xcopy C:\xampp\htdocs\dev\dennis\user_access.php C:\xampp\htdocs\prod\dennis\user_access.php /d /y
xcopy C:\xampp\htdocs\dev\dennis\user_options.html C:\xampp\htdocs\prod\dennis\user_options.html /d /y
xcopy C:\xampp\htdocs\dev\boldb.sql C:\xampp\htdocs\prod\boldb.sql /d /y
xcopy C:\xampp\htdocs\dev\Create_script.sql C:\xampp\htdocs\prod\Create_script.sql /d /y
pause